version: "3"
services:
  eureka-server:
    build: ./eureka-server
    deploy:
      replicas: 1
    ports:
      - 8761:8761
    environment:
     - SERVER_PORT=8761
     - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
     - EUREKA_CLIENT_FETCH_REGISTRY=false
  